name: clean
description: "A simple way to clean your photos."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.0.0
  image: ^4.7.2
  crypto: ^3.0.3
  google_fonts: ^6.3.2
  disk_space_plus: ^0.2.6
  google_mlkit_face_detection: ^0.13.1
  device_info_plus: ^12.3.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  shared_preferences: ^2.5.4
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.5
  provider: ^6.1.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#1A1D1B"
  image: "assets/images/logo_mk_4_splashscreen.png"
  android_gravity: center

  android_12:
    image: "assets/images/logo_mk_4_splashscreen.png"
    icon_background_color: "#1A1D1B"
    color: "#1A1D1B"
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo mk 4.png"